name = "SparseMatricesCOO"
uuid = "fa32481b-f100-4b48-8dc8-c62f61b13870"
authors = ["Dominique Orban <dominique.orban@gmail.com> and contributors"]
version = "0.2.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1.10"
SparseArrays = "1.10"
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
